// Generated by gencpp from file mowei_msgs/getLinearActuatorStatus.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETLINEARACTUATORSTATUS_H
#define MOWEI_MSGS_MESSAGE_GETLINEARACTUATORSTATUS_H

#include <ros/service_traits.h>


#include <mowei_msgs/getLinearActuatorStatusRequest.h>
#include <mowei_msgs/getLinearActuatorStatusResponse.h>


namespace mowei_msgs
{

struct getLinearActuatorStatus
{

typedef getLinearActuatorStatusRequest Request;
typedef getLinearActuatorStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLinearActuatorStatus
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorStatus > {
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::mowei_msgs::getLinearActuatorStatus&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getLinearActuatorStatus > {
  static const char* value()
  {
    return "mowei_msgs/getLinearActuatorStatus";
  }

  static const char* value(const ::mowei_msgs::getLinearActuatorStatus&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorStatusRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorStatus > 
template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getLinearActuatorStatus >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getLinearActuatorStatusRequest> should match 
// service_traits::DataType< ::mowei_msgs::getLinearActuatorStatus > 
template<>
struct DataType< ::mowei_msgs::getLinearActuatorStatusRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getLinearActuatorStatus >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorStatusResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorStatus > 
template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getLinearActuatorStatus >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getLinearActuatorStatusResponse> should match 
// service_traits::DataType< ::mowei_msgs::getLinearActuatorStatus > 
template<>
struct DataType< ::mowei_msgs::getLinearActuatorStatusResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getLinearActuatorStatus >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETLINEARACTUATORSTATUS_H
