// Generated by gencpp from file mowei_msgs/getLinearActuatorIsLock.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETLINEARACTUATORISLOCK_H
#define MOWEI_MSGS_MESSAGE_GETLINEARACTUATORISLOCK_H

#include <ros/service_traits.h>


#include <mowei_msgs/getLinearActuatorIsLockRequest.h>
#include <mowei_msgs/getLinearActuatorIsLockResponse.h>


namespace mowei_msgs
{

struct getLinearActuatorIsLock
{

typedef getLinearActuatorIsLockRequest Request;
typedef getLinearActuatorIsLockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLinearActuatorIsLock
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorIsLock > {
  static const char* value()
  {
    return "0b13460cb14006d3852674b4c614f25f";
  }

  static const char* value(const ::mowei_msgs::getLinearActuatorIsLock&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getLinearActuatorIsLock > {
  static const char* value()
  {
    return "mowei_msgs/getLinearActuatorIsLock";
  }

  static const char* value(const ::mowei_msgs::getLinearActuatorIsLock&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorIsLockRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorIsLock > 
template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorIsLockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getLinearActuatorIsLock >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorIsLockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getLinearActuatorIsLockRequest> should match 
// service_traits::DataType< ::mowei_msgs::getLinearActuatorIsLock > 
template<>
struct DataType< ::mowei_msgs::getLinearActuatorIsLockRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getLinearActuatorIsLock >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorIsLockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorIsLockResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::getLinearActuatorIsLock > 
template<>
struct MD5Sum< ::mowei_msgs::getLinearActuatorIsLockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getLinearActuatorIsLock >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorIsLockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getLinearActuatorIsLockResponse> should match 
// service_traits::DataType< ::mowei_msgs::getLinearActuatorIsLock > 
template<>
struct DataType< ::mowei_msgs::getLinearActuatorIsLockResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getLinearActuatorIsLock >::value();
  }
  static const char* value(const ::mowei_msgs::getLinearActuatorIsLockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETLINEARACTUATORISLOCK_H
