// Generated by gencpp from file mowei_msgs/getMobileBaseMoveForPosition1.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION1_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION1_H

#include <ros/service_traits.h>


#include <mowei_msgs/getMobileBaseMoveForPosition1Request.h>
#include <mowei_msgs/getMobileBaseMoveForPosition1Response.h>


namespace mowei_msgs
{

struct getMobileBaseMoveForPosition1
{

typedef getMobileBaseMoveForPosition1Request Request;
typedef getMobileBaseMoveForPosition1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMobileBaseMoveForPosition1
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1 > {
  static const char* value()
  {
    return "87f3f4f6b09536e1db996bb828372de5";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition1 > {
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseMoveForPosition1";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1Request> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1 > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1Request>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition1Request> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition1 > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition1Request>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForPosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1Response> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1 > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1Response>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition1Response> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition1 > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition1Response>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForPosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION1_H
