// Generated by gencpp from file mowei_msgs/getMobileBaseBatteryCapacityResponse.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEBATTERYCAPACITYRESPONSE_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEBATTERYCAPACITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct getMobileBaseBatteryCapacityResponse_
{
  typedef getMobileBaseBatteryCapacityResponse_<ContainerAllocator> Type;

  getMobileBaseBatteryCapacityResponse_()
    : capacity(0)  {
    }
  getMobileBaseBatteryCapacityResponse_(const ContainerAllocator& _alloc)
    : capacity(0)  {
  (void)_alloc;
    }



   typedef int8_t _capacity_type;
  _capacity_type capacity;




  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getMobileBaseBatteryCapacityResponse_

typedef ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<std::allocator<void> > getMobileBaseBatteryCapacityResponse;

typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseBatteryCapacityResponse > getMobileBaseBatteryCapacityResponsePtr;
typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseBatteryCapacityResponse const> getMobileBaseBatteryCapacityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "facd9d25e71b5e79fad5e0fc8b8aab8e";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfacd9d25e71b5e79ULL;
  static const uint64_t static_value2 = 0xfad5e0fc8b8aab8eULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseBatteryCapacityResponse";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 capacity\n\
\n\
";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.capacity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMobileBaseBatteryCapacityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::getMobileBaseBatteryCapacityResponse_<ContainerAllocator>& v)
  {
    s << indent << "capacity: ";
    Printer<int8_t>::stream(s, indent + "  ", v.capacity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEBATTERYCAPACITYRESPONSE_H
