// Generated by gencpp from file mowei_msgs/getMobileBaseMoveForSpeedResponse.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEEDRESPONSE_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct getMobileBaseMoveForSpeedResponse_
{
  typedef getMobileBaseMoveForSpeedResponse_<ContainerAllocator> Type;

  getMobileBaseMoveForSpeedResponse_()
    : output()  {
    }
  getMobileBaseMoveForSpeedResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _output_type;
  _output_type output;




  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getMobileBaseMoveForSpeedResponse_

typedef ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<std::allocator<void> > getMobileBaseMoveForSpeedResponse;

typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseMoveForSpeedResponse > getMobileBaseMoveForSpeedResponsePtr;
typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseMoveForSpeedResponse const> getMobileBaseMoveForSpeedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87f3f4f6b09536e1db996bb828372de5";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87f3f4f6b09536e1ULL;
  static const uint64_t static_value2 = 0xdb996bb828372de5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseMoveForSpeedResponse";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] output\n\
\n\
";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMobileBaseMoveForSpeedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::getMobileBaseMoveForSpeedResponse_<ContainerAllocator>& v)
  {
    s << indent << "output[]" << std::endl;
    for (size_t i = 0; i < v.output.size(); ++i)
    {
      s << indent << "  output[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.output[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEEDRESPONSE_H
