// Generated by gencpp from file mowei_msgs/getMobileBaseMoveForSpeed.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEED_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEED_H

#include <ros/service_traits.h>


#include <mowei_msgs/getMobileBaseMoveForSpeedRequest.h>
#include <mowei_msgs/getMobileBaseMoveForSpeedResponse.h>


namespace mowei_msgs
{

struct getMobileBaseMoveForSpeed
{

typedef getMobileBaseMoveForSpeedRequest Request;
typedef getMobileBaseMoveForSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMobileBaseMoveForSpeed
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeed > {
  static const char* value()
  {
    return "87f3f4f6b09536e1db996bb828372de5";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeed&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForSpeed > {
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseMoveForSpeed";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeedRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeed > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForSpeedRequest> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForSpeed > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeedResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeed > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForSpeedResponse> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForSpeed > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORSPEED_H
