// Generated by gencpp from file mowei_msgs/getMobileBaseMoveForPosition2.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION2_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION2_H

#include <ros/service_traits.h>


#include <mowei_msgs/getMobileBaseMoveForPosition2Request.h>
#include <mowei_msgs/getMobileBaseMoveForPosition2Response.h>


namespace mowei_msgs
{

struct getMobileBaseMoveForPosition2
{

typedef getMobileBaseMoveForPosition2Request Request;
typedef getMobileBaseMoveForPosition2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMobileBaseMoveForPosition2
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2 > {
  static const char* value()
  {
    return "87f3f4f6b09536e1db996bb828372de5";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition2 > {
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseMoveForPosition2";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2Request> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2 > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2Request>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition2Request> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition2 > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition2Request>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForPosition2 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2Response> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2 > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2Response>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveForPosition2 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition2Response> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveForPosition2 > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveForPosition2Response>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveForPosition2 >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveForPosition2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEFORPOSITION2_H
