// Generated by gencpp from file mowei_msgs/getMobileBaseOcIsEnableResponse.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEOCISENABLERESPONSE_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEOCISENABLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct getMobileBaseOcIsEnableResponse_
{
  typedef getMobileBaseOcIsEnableResponse_<ContainerAllocator> Type;

  getMobileBaseOcIsEnableResponse_()
    : enabled(0)  {
    }
  getMobileBaseOcIsEnableResponse_(const ContainerAllocator& _alloc)
    : enabled(0)  {
  (void)_alloc;
    }



   typedef int8_t _enabled_type;
  _enabled_type enabled;




  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getMobileBaseOcIsEnableResponse_

typedef ::mowei_msgs::getMobileBaseOcIsEnableResponse_<std::allocator<void> > getMobileBaseOcIsEnableResponse;

typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseOcIsEnableResponse > getMobileBaseOcIsEnableResponsePtr;
typedef boost::shared_ptr< ::mowei_msgs::getMobileBaseOcIsEnableResponse const> getMobileBaseOcIsEnableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6443b0eeced033f2bdf37f5297439af";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6443b0eeced033fULL;
  static const uint64_t static_value2 = 0x2bdf37f5297439afULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseOcIsEnableResponse";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enabled\n\
\n\
";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getMobileBaseOcIsEnableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::getMobileBaseOcIsEnableResponse_<ContainerAllocator>& v)
  {
    s << indent << "enabled: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEOCISENABLERESPONSE_H
