// Generated by gencpp from file mowei_msgs/getMobileBaseMoveMode.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEMODE_H
#define MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEMODE_H

#include <ros/service_traits.h>


#include <mowei_msgs/getMobileBaseMoveModeRequest.h>
#include <mowei_msgs/getMobileBaseMoveModeResponse.h>


namespace mowei_msgs
{

struct getMobileBaseMoveMode
{

typedef getMobileBaseMoveModeRequest Request;
typedef getMobileBaseMoveModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMobileBaseMoveMode
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveMode > {
  static const char* value()
  {
    return "418c02483a8ca57215fb7b31c5c87234";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveMode&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveMode > {
  static const char* value()
  {
    return "mowei_msgs/getMobileBaseMoveMode";
  }

  static const char* value(const ::mowei_msgs::getMobileBaseMoveMode&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveModeRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveMode > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveModeRequest> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveMode > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveModeRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveModeResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::getMobileBaseMoveMode > 
template<>
struct MD5Sum< ::mowei_msgs::getMobileBaseMoveModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::getMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveModeResponse> should match 
// service_traits::DataType< ::mowei_msgs::getMobileBaseMoveMode > 
template<>
struct DataType< ::mowei_msgs::getMobileBaseMoveModeResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::getMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::getMobileBaseMoveModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_GETMOBILEBASEMOVEMODE_H
