// Generated by gencpp from file mowei_msgs/setLinearActuatorPos.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETLINEARACTUATORPOS_H
#define MOWEI_MSGS_MESSAGE_SETLINEARACTUATORPOS_H

#include <ros/service_traits.h>


#include <mowei_msgs/setLinearActuatorPosRequest.h>
#include <mowei_msgs/setLinearActuatorPosResponse.h>


namespace mowei_msgs
{

struct setLinearActuatorPos
{

typedef setLinearActuatorPosRequest Request;
typedef setLinearActuatorPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setLinearActuatorPos
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorPos > {
  static const char* value()
  {
    return "19a5a22d8c3ec179b243df3885063a64";
  }

  static const char* value(const ::mowei_msgs::setLinearActuatorPos&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setLinearActuatorPos > {
  static const char* value()
  {
    return "mowei_msgs/setLinearActuatorPos";
  }

  static const char* value(const ::mowei_msgs::setLinearActuatorPos&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorPosRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorPos > 
template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setLinearActuatorPos >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setLinearActuatorPosRequest> should match 
// service_traits::DataType< ::mowei_msgs::setLinearActuatorPos > 
template<>
struct DataType< ::mowei_msgs::setLinearActuatorPosRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setLinearActuatorPos >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorPosResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorPos > 
template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setLinearActuatorPos >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setLinearActuatorPosResponse> should match 
// service_traits::DataType< ::mowei_msgs::setLinearActuatorPos > 
template<>
struct DataType< ::mowei_msgs::setLinearActuatorPosResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setLinearActuatorPos >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETLINEARACTUATORPOS_H
