// Generated by gencpp from file mowei_msgs/setLinearActuatorLock.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETLINEARACTUATORLOCK_H
#define MOWEI_MSGS_MESSAGE_SETLINEARACTUATORLOCK_H

#include <ros/service_traits.h>


#include <mowei_msgs/setLinearActuatorLockRequest.h>
#include <mowei_msgs/setLinearActuatorLockResponse.h>


namespace mowei_msgs
{

struct setLinearActuatorLock
{

typedef setLinearActuatorLockRequest Request;
typedef setLinearActuatorLockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setLinearActuatorLock
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorLock > {
  static const char* value()
  {
    return "40a517f2d5fa9b40c59c519c0a25ebc1";
  }

  static const char* value(const ::mowei_msgs::setLinearActuatorLock&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setLinearActuatorLock > {
  static const char* value()
  {
    return "mowei_msgs/setLinearActuatorLock";
  }

  static const char* value(const ::mowei_msgs::setLinearActuatorLock&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorLockRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorLock > 
template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorLockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setLinearActuatorLock >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorLockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setLinearActuatorLockRequest> should match 
// service_traits::DataType< ::mowei_msgs::setLinearActuatorLock > 
template<>
struct DataType< ::mowei_msgs::setLinearActuatorLockRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setLinearActuatorLock >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorLockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorLockResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setLinearActuatorLock > 
template<>
struct MD5Sum< ::mowei_msgs::setLinearActuatorLockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setLinearActuatorLock >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorLockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setLinearActuatorLockResponse> should match 
// service_traits::DataType< ::mowei_msgs::setLinearActuatorLock > 
template<>
struct DataType< ::mowei_msgs::setLinearActuatorLockResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setLinearActuatorLock >::value();
  }
  static const char* value(const ::mowei_msgs::setLinearActuatorLockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETLINEARACTUATORLOCK_H
