// Generated by gencpp from file mowei_msgs/setMobileBaseLock.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASELOCK_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASELOCK_H

#include <ros/service_traits.h>


#include <mowei_msgs/setMobileBaseLockRequest.h>
#include <mowei_msgs/setMobileBaseLockResponse.h>


namespace mowei_msgs
{

struct setMobileBaseLock
{

typedef setMobileBaseLockRequest Request;
typedef setMobileBaseLockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMobileBaseLock
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseLock > {
  static const char* value()
  {
    return "40a517f2d5fa9b40c59c519c0a25ebc1";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseLock&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setMobileBaseLock > {
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseLock";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseLock&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseLockRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseLock > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseLockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseLock >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseLockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseLockRequest> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseLock > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseLockRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseLock >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseLockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseLockResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseLock > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseLockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseLock >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseLockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseLockResponse> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseLock > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseLockResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseLock >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseLockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASELOCK_H
