// Generated by gencpp from file mowei_msgs/setMobileBaseMovePosition1Request.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1REQUEST_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct setMobileBaseMovePosition1Request_
{
  typedef setMobileBaseMovePosition1Request_<ContainerAllocator> Type;

  setMobileBaseMovePosition1Request_()
    : x(0)
    , y(0)
    , speed(0)  {
    }
  setMobileBaseMovePosition1Request_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int8_t _x_type;
  _x_type x;

   typedef int8_t _y_type;
  _y_type y;

   typedef int8_t _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> const> ConstPtr;

}; // struct setMobileBaseMovePosition1Request_

typedef ::mowei_msgs::setMobileBaseMovePosition1Request_<std::allocator<void> > setMobileBaseMovePosition1Request;

typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMovePosition1Request > setMobileBaseMovePosition1RequestPtr;
typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMovePosition1Request const> setMobileBaseMovePosition1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5cd25cdc4bb8ed365b3e3032aef3bb5";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5cd25cdc4bb8ed3ULL;
  static const uint64_t static_value2 = 0x65b3e3032aef3bb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMovePosition1Request";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 x\n\
int8 y\n\
int8 speed\n\
";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setMobileBaseMovePosition1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::setMobileBaseMovePosition1Request_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1REQUEST_H
