// Generated by gencpp from file mowei_msgs/setMobileBaseMoveMode.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODE_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODE_H

#include <ros/service_traits.h>


#include <mowei_msgs/setMobileBaseMoveModeRequest.h>
#include <mowei_msgs/setMobileBaseMoveModeResponse.h>


namespace mowei_msgs
{

struct setMobileBaseMoveMode
{

typedef setMobileBaseMoveModeRequest Request;
typedef setMobileBaseMoveModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMobileBaseMoveMode
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveMode > {
  static const char* value()
  {
    return "40a517f2d5fa9b40c59c519c0a25ebc1";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveMode&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveMode > {
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMoveMode";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveMode&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveModeRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveMode > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveModeRequest> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveMode > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveModeRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveModeResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveMode > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveModeResponse> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveMode > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveModeResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMoveMode >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODE_H
