// Generated by gencpp from file mowei_msgs/setMobileBaseOcenable.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEOCENABLE_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEOCENABLE_H

#include <ros/service_traits.h>


#include <mowei_msgs/setMobileBaseOcenableRequest.h>
#include <mowei_msgs/setMobileBaseOcenableResponse.h>


namespace mowei_msgs
{

struct setMobileBaseOcenable
{

typedef setMobileBaseOcenableRequest Request;
typedef setMobileBaseOcenableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMobileBaseOcenable
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseOcenable > {
  static const char* value()
  {
    return "40a517f2d5fa9b40c59c519c0a25ebc1";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseOcenable&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setMobileBaseOcenable > {
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseOcenable";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseOcenable&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseOcenableRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseOcenable > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseOcenableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseOcenable >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseOcenableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseOcenableRequest> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseOcenable > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseOcenableRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseOcenable >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseOcenableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseOcenableResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseOcenable > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseOcenableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseOcenable >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseOcenableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseOcenableResponse> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseOcenable > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseOcenableResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseOcenable >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseOcenableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEOCENABLE_H
