// Generated by gencpp from file mowei_msgs/setMobileBaseMovePosition1.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1_H

#include <ros/service_traits.h>


#include <mowei_msgs/setMobileBaseMovePosition1Request.h>
#include <mowei_msgs/setMobileBaseMovePosition1Response.h>


namespace mowei_msgs
{

struct setMobileBaseMovePosition1
{

typedef setMobileBaseMovePosition1Request Request;
typedef setMobileBaseMovePosition1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMobileBaseMovePosition1
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1 > {
  static const char* value()
  {
    return "463a9a92d546cf8ab23ffc3c760cf798";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setMobileBaseMovePosition1 > {
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMovePosition1";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1Request> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1 > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1Request>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMovePosition1Request> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMovePosition1 > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMovePosition1Request>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMovePosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1Response> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1 > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1Response>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMovePosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMovePosition1Response> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMovePosition1 > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMovePosition1Response>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMovePosition1 >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMovePosition1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEPOSITION1_H
