// Generated by gencpp from file mowei_msgs/setMobileBaseMoveForSpeed.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEED_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEED_H

#include <ros/service_traits.h>


#include <mowei_msgs/setMobileBaseMoveForSpeedRequest.h>
#include <mowei_msgs/setMobileBaseMoveForSpeedResponse.h>


namespace mowei_msgs
{

struct setMobileBaseMoveForSpeed
{

typedef setMobileBaseMoveForSpeedRequest Request;
typedef setMobileBaseMoveForSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMobileBaseMoveForSpeed
} // namespace mowei_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeed > {
  static const char* value()
  {
    return "2f14e357f3024271a74355e0c88a1f90";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeed&) { return value(); }
};

template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveForSpeed > {
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMoveForSpeed";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeedRequest> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeed > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveForSpeedRequest> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveForSpeed > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveForSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeedResponse> should match 
// service_traits::MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeed > 
template<>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveForSpeedResponse> should match 
// service_traits::DataType< ::mowei_msgs::setMobileBaseMoveForSpeed > 
template<>
struct DataType< ::mowei_msgs::setMobileBaseMoveForSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::mowei_msgs::setMobileBaseMoveForSpeed >::value();
  }
  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEED_H
