// Generated by gencpp from file mowei_msgs/setMobileBaseMoveModeRequest.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODEREQUEST_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct setMobileBaseMoveModeRequest_
{
  typedef setMobileBaseMoveModeRequest_<ContainerAllocator> Type;

  setMobileBaseMoveModeRequest_()
    : fun(0)  {
    }
  setMobileBaseMoveModeRequest_(const ContainerAllocator& _alloc)
    : fun(0)  {
  (void)_alloc;
    }



   typedef int8_t _fun_type;
  _fun_type fun;




  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setMobileBaseMoveModeRequest_

typedef ::mowei_msgs::setMobileBaseMoveModeRequest_<std::allocator<void> > setMobileBaseMoveModeRequest;

typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveModeRequest > setMobileBaseMoveModeRequestPtr;
typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveModeRequest const> setMobileBaseMoveModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0db200d26ad3bf52dd0a578ba9b6b00";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0db200d26ad3bf5ULL;
  static const uint64_t static_value2 = 0x2dd0a578ba9b6b00ULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMoveModeRequest";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 fun\n\
";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fun);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setMobileBaseMoveModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::setMobileBaseMoveModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "fun: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fun);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEMODEREQUEST_H
