// Generated by gencpp from file mowei_msgs/setMobileBaseMoveForSpeedRequest.msg
// DO NOT EDIT!


#ifndef MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEEDREQUEST_H
#define MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mowei_msgs
{
template <class ContainerAllocator>
struct setMobileBaseMoveForSpeedRequest_
{
  typedef setMobileBaseMoveForSpeedRequest_<ContainerAllocator> Type;

  setMobileBaseMoveForSpeedRequest_()
    : xSpeed(0)
    , ySpeed(0)
    , zSpeed(0)  {
    }
  setMobileBaseMoveForSpeedRequest_(const ContainerAllocator& _alloc)
    : xSpeed(0)
    , ySpeed(0)
    , zSpeed(0)  {
  (void)_alloc;
    }



   typedef int8_t _xSpeed_type;
  _xSpeed_type xSpeed;

   typedef int8_t _ySpeed_type;
  _ySpeed_type ySpeed;

   typedef int8_t _zSpeed_type;
  _zSpeed_type zSpeed;




  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setMobileBaseMoveForSpeedRequest_

typedef ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<std::allocator<void> > setMobileBaseMoveForSpeedRequest;

typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveForSpeedRequest > setMobileBaseMoveForSpeedRequestPtr;
typedef boost::shared_ptr< ::mowei_msgs::setMobileBaseMoveForSpeedRequest const> setMobileBaseMoveForSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mowei_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da18ffc85ed32bc20ff02d53f280e41b";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda18ffc85ed32bc2ULL;
  static const uint64_t static_value2 = 0x0ff02d53f280e41bULL;
};

template<class ContainerAllocator>
struct DataType< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mowei_msgs/setMobileBaseMoveForSpeedRequest";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 xSpeed\n\
int8 ySpeed\n\
int8 zSpeed\n\
";
  }

  static const char* value(const ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xSpeed);
      stream.next(m.ySpeed);
      stream.next(m.zSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setMobileBaseMoveForSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mowei_msgs::setMobileBaseMoveForSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "xSpeed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.xSpeed);
    s << indent << "ySpeed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ySpeed);
    s << indent << "zSpeed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.zSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOWEI_MSGS_MESSAGE_SETMOBILEBASEMOVEFORSPEEDREQUEST_H
